In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [2]:
d_train=pd.read_csv("Google_Stock_Price_Train.csv")
d_test=pd.read_csv("Google_Stock_Price_Test.csv")

In [3]:
print(d_train)

            Date    Open    High     Low   Close      Volume
0       1/3/2012  325.25  332.83  324.97  663.59   7380500.0
1       1/4/2012  331.27  333.87  329.08  666.45   5749400.0
2       1/5/2012  329.83  330.75  326.89  657.21   6590300.0
3       1/6/2012  328.34  328.77  323.68  648.24   5405900.0
4       1/9/2012  322.04  322.29  309.46  620.76  11688800.0
...          ...     ...     ...     ...     ...         ...
1253  12/23/2016  790.90  792.74  787.28  789.91    623400.0
1254  12/27/2016  790.68  797.86  787.66  791.55    789100.0
1255  12/28/2016  793.70  794.23  783.20  785.05   1153800.0
1256  12/29/2016  783.33  785.93  778.92  782.79    744300.0
1257  12/30/2016  782.75  782.78  770.41  771.82   1770000.0

[1258 rows x 6 columns]


In [4]:
print(d_test)

         Date    Open    High     Low   Close     Volume
0    1/3/2017  778.81  789.63  775.80  786.14  1657300.0
1    1/4/2017  788.36  791.34  783.16  786.90  1073000.0
2    1/5/2017  786.08  794.48  785.02  794.02  1335200.0
3    1/6/2017  795.26  807.90  792.20  806.15  1640200.0
4    1/9/2017  806.40  809.97  802.83  806.65  1272400.0
5   1/10/2017  807.86  809.13  803.51  804.79  1176800.0
6   1/11/2017  805.00  808.15  801.37  807.91  1065900.0
7   1/12/2017  807.14  807.39  799.17  806.36  1353100.0
8   1/13/2017  807.48  811.22  806.69  807.88  1099200.0
9   1/17/2017  807.08  807.14  800.37  804.61  1362100.0
10  1/18/2017  805.81  806.21  800.99  806.07  1294400.0
11  1/19/2017  805.12  809.48  801.80  802.17   919300.0
12  1/20/2017  806.91  806.91  801.69  805.02  1670000.0
13  1/23/2017  807.25  820.87  803.74  819.31  1963600.0
14  1/24/2017  822.30  825.90  817.82  823.87  1474000.0
15  1/25/2017  829.62  835.77  825.06  835.67  1494500.0
16  1/26/2017  837.81  838.00  

In [5]:
print(d_train.isnull().sum())

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64


In [6]:
print(d_test.isnull().sum())

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64


In [7]:
X_train=d_train[['Open','High','Low','Volume']].values
y_train=d_train.iloc[:,4:5].values

X_test=d_test[['Open','High','Low','Volume']].values
y_test=d_test.iloc[:,4:5].values

In [8]:
print(X_train)

[[3.2525e+02 3.3283e+02 3.2497e+02 7.3805e+06]
 [3.3127e+02 3.3387e+02 3.2908e+02 5.7494e+06]
 [3.2983e+02 3.3075e+02 3.2689e+02 6.5903e+06]
 ...
 [7.9370e+02 7.9423e+02 7.8320e+02 1.1538e+06]
 [7.8333e+02 7.8593e+02 7.7892e+02 7.4430e+05]
 [7.8275e+02 7.8278e+02 7.7041e+02 1.7700e+06]]


In [9]:
m=LinearRegression()
m.fit(X_train,y_train)

LinearRegression()

In [10]:
y_pred=m.predict(X_test)
print(y_pred)

[[754.40588319]
 [798.71235287]
 [795.07824942]
 [743.57927405]
 [829.4820455 ]
 [842.971888  ]
 [824.66560288]
 [819.38288804]
 [853.16453882]
 [836.00568628]
 [850.32137505]
 [809.50764   ]
 [865.09686812]
 [747.53742228]
 [836.37799812]
 [813.03267399]
 [868.59517571]
 [750.37950626]
 [807.90366731]
 [817.04218114]]


In [11]:
print(y_test)

[[786.14]
 [786.9 ]
 [794.02]
 [806.15]
 [806.65]
 [804.79]
 [807.91]
 [806.36]
 [807.88]
 [804.61]
 [806.07]
 [802.17]
 [805.02]
 [819.31]
 [823.87]
 [835.67]
 [832.15]
 [823.31]
 [802.32]
 [796.79]]


In [12]:
RMSE = ( mean_squared_error(y_test,y_pred))**0.5
print('Root Mean Square Error :',RMSE)
print('Root Mean Sqare Error(%) :',float(RMSE),"%")

Root Mean Square Error : 38.1173040769204
Root Mean Sqare Error(%) : 38.1173040769204 %
